coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        base: auto
comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: "coverage_drop OR uncovered_patch"
  require_base: false
  require_head: true
  hide_project_coverage: false
