version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"                # Location of requirements.txt or pyproject.toml
    schedule:
      interval: "weekly"
    groups:
      all-pip-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
      - "python"
  - package-ecosystem: "github-actions"
    directory: "/"                # Location of GitHub Actions workflows
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: ["*"]
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"