# .github/workflows/publish.yml
name: Publish Python Package

on:
  workflow_dispatch:
    inputs:
      artifact_run_id:
        description: 'Workflow run ID to download artifact from'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Download built package artifact from workflow run
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-and-test.yml
          run_id: ${{ github.event.inputs.artifact_run_id }}
          name: python-dist
          path: dist/
          github_token: ${{ secrets.ACTION_API_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Publish package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install twine
          twine upload dist/*

      - name: Generate checksums for dist files
        run: |
          for file in dist/*; do
            sha256sum "$file" > "dist/$(basename "$file").sha256"
          done

      - name: Create GitHub Release Draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}