# .github/workflows/publish.yml
name: Publish Python Package

on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Download built package artifact
        uses: actions/download-artifact@v4
        with:
          name: python-dist
          path: dist/

      - name: Publish package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install twine
          twine upload dist/*